### ISSUE TITLE
etn --testnet can't find peer

### ISSUE THREAD

**Issue by ang-st** [electroneum/electroneum#115]
Hi,
Is there a testnet available ? where can i find dns seed or peer to bootstrap ?
Thanks

**Comment by electroneumRepo** [comment]
Hi,

Currently there is no testnet setup.

You can create a testnet your self by compiling this repo yourself, you'll need to specify a minimum of 2 IP addresses in the `src/p2p/net_node.inl` file in the if statement for testnet.

Unfortunately we cannot provide you with direct support for creating a testnet as it requires a fair bit of technical knowledge.

**Comment by TriJetScud** [comment]
If you want to simulate a testnet locally you can always try starting electroneumd like this:

`./electroneumd --testnet --seed-node 127.0.0.1`

This will force the daemon to use itself as a seed node. Since the daemon has no prior knowledge on the testnet, it will effectively be a clean testnet for testing whatever integrations you plan to use with electroneum or as a matter of fact, any CryptoNote derived coins
