### ISSUE TITLE
Error code 16

### ISSUE THREAD

**Issue by noverion** [electroneum/electroneum#133]
Im trying to send some tokens to Cryptopia. I got this error message and canot do anything .Someone got a clue`?

Best regards

**Comment by HeidemannMarkus** [comment]
I tried to send to my offline-wallet. 

the transaction failed and the etn is removed (!) from my wallet 

no transaction information is provided... that leaves a bad feeling

**Comment by flyingfork21** [comment]
Hi,
Transaction failed with error code 16 and coins disappeared but noone received it.
What is wrong ?

**Comment by HeidemannMarkus** [comment]
@flyingfork21 hey,
are you asking for more details - or do you have the same problem?

**Comment by Invisible75** [comment]
Hi Flyingfork21, dit you get your coins back? I have same problem error 16 but i dont see my coins in my wallet or in cryptopia

**Comment by Invisible75** [comment]
@flyingfork21  did you get your coins back? I have same problem error 16 but i dont see my coins in my wallet or in cryptopia

**Comment by Invisible75** [comment]
@noverion You did receive your coins?

**Comment by flyingfork21** [comment]
Hi @HeidemannMarkus 
I have the same problem. Since the first failed transaction my wallet is unusable.
Coins disappear from wallet and transaction failed with error code 16. 

Please see screen capture
![image](https://user-images.githubusercontent.com/21297473/36162818-cda1c11a-10e7-11e8-9140-75a1a5a9dfc2.png)

**Comment by flyingfork21** [comment]
@Invisible75 
My problem is sending coins I already had confirmed in my wallet.
So no the problem is still not solved.

**Comment by ghost** [comment]
Someone access in my account and made a transaction looks like trying to steal my wallet balances. but suddenly the transaction is "failed error code 16" and my coins is gone. I belive this error happens only  when you try to transfer ETN to hack or steal coins from others, it is failed because you did it by bypassing pin or transferring using the method of hacking.

**Comment by regelaar** [comment]
Same problem, Sent 1000 ETN, error 16, money is gone

EDIT: I received it :)

**Comment by ChrisM0678** [comment]
Having the same issue, tried sending some ETN to Cryptopia and coins were removed from the wallet but got an Error 16 a few minutes later. Any update on the solution or how to get my coins back?

**Comment by Unyxos** [comment]
The error code 16 is just a visual glitch, your transaction is processed :) you can check that by the TX Hash being generated, your coins are sent to the provided address, don’t worry, your coins aren’t lost !

**Comment by fitzski** [comment]
@Unyxos This has just happened to me too when I tried to send to Cryptopia - "This transaction failed with error code 16" -  failed transaction. How long typically should it take for the ETN to arrive in Cryptopia?

**Comment by ChrisM0678** [comment]
@Unyxos Unfortunately I don't think that's the case, Cryptopia usually credits the deposit at most within an hour of sending it and it's still shows that nothing has arrived.

**Comment by KhmerRun** [comment]
I had the same issue yesterday.
1) sent from electroneum web wallet. Transaction said failed but my balance got deduced as per sent amount.
2) withdraw from cryptopia.

Nothing arrive into my wallet yet till today. Ticket submitted also.

**Comment by ChrisM0678** [comment]
@KhmerRun Sounds like yours actually arrived at Cryptopia, mine did not nor did the amount sent ever get put back into my web wallet.

When looking at the  TX Hash it shows it's been confirmed 261 times as of this message but it's no where to be found.

**Comment by flyingfork21** [comment]
Anyone has news or solution about this?
Coins are still missing, transaction still show as failed with error code 16.
What does this error code refer to ?

**Comment by flyingfork21** [comment]
@regelaar how did it solve ?

**Comment by regelaar** [comment]
It just appeared on my Cryptopia account.

**Comment by fitzski** [comment]
Mine just appeared too after about 12 hours

**Comment by flyingfork21** [comment]
@regelaar @fitzski 
and now whe you push new transactions do they show as failed or ok ?

**Comment by ChrisM0678** [comment]
Mine appeared in Cryptopia this morning. Tried sending more over just to see if the problem had resolved itself and it has not. Transaction is marked as Failed and I guess I have to play the waiting game again.

**Comment by martinvenus** [comment]
I have the same problem. I've sent money to offline wallet, transaction failed with code 16, money are not in offline wallet and current balance does not contain money from the failed transaction. I'm already waiting for more than a week, but money seems to be lost.

I've created a support ticket #38816 but no response at all.

**Comment by Invisible75** [comment]
Hi there

 

I get it after 2 days, so I think it willc ome

 

 

 

 

 

Met vriendelijke groet / Beste regards,         

 

Invest Group

Trig-R

Groothandelsgebouw
Weena 737
3013 AM Rotterdam – NL

Tel:   +31 (0)10 268 06 61

 <mailto:invest@trig-r.com> invest@trig-r.com
 <http://www.trig-r.com/> www.trig-r.com

 

 

 <https://www.linkedin.com/in/pascal-van-der-knaap-87424111/> 

 

 

 

 

Van: Martin Venuš [mailto:notifications@github.com] 
Verzonden: zaterdag 17 februari 2018 20:44
Aan: electroneum/electroneum <electroneum@noreply.github.com>
CC: Invisible75 <invest@trig-r.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [electroneum/electroneum] Error code 16 (#133)

 

I have the same problem. I've sent money to offline wallet, transaction failed with code 16, money are not in offline wallet and current balance does not contain money from the failed transaction. I'm already waiting for more than a week, but money seems to be lost.

I've created a support ticket #38816 but no response at all.

**Comment by basanta2727** [comment]
Barbs (Electroneum)

Apr 4, 3:43 PM BST

Hi Basantaswain5115

We are sorry to hear that it looks as though your account has been hacked- this is likely due to a phishing attack. Unfortunately phishing attacks are becoming more and more sophisticated and it is important that you protect yourself and your devices from potential future threats,

Please remember all official information will be announced either on our blog or our social media which can be found here: 

https://electroneum.com/blog 
https://www.facebook.com/electroneum
https://twitter.com/electroneum

If you found that your balance has been cleared due to phishing attack please ensure you read the link attached, to help ensure the safety of your ETN and your account in future: protect yourself against phishing.

Before logging in to your my.Electroneum.com account, please ensure you have read and confirmed the following before proceeding further.

​

Kind regards,

Barbs
