### ISSUE TITLE
Cryptopia deposit issues

### ISSUE THREAD

**Issue by MynxGithub** [electroneum/electroneum#151]
I've sent 1,000 ETN to cryptopia via the online wallet my.electroneum.com

![image](https://user-images.githubusercontent.com/35780058/36546425-4bc7e1da-17e3-11e8-900c-c0935c4160bb.png)

Yet on Cryptopia, it's not showing in my balance. The deposit address is correct so is the payment ID (transaction is viewable and shown as completed on blockexplorer). Is it an issue on their end? a couple of coins on Cryptopia are starting to become stuck there I've noticed...

**Comment by jpeter12** [comment]
Dude, it's a cryptopia problem. They have paused ETN transactions.
Check "COIN INFO" on cryptopia and you will see that ETN is in maintenance.

**Comment by jpeter12** [comment]
DEVs please also close this issue as it's not related to electroneum daemon.

**Comment by angelhvargas** [comment]
Nice! this is how this guys replied to you! Closing the ticket LOL

**Comment by jpeter12** [comment]
@angelhvargas As stated above, Cryptopia are having problems with their ETN installation. It has ABSOLUTELY NOTHING to do with this repository. Stop spamming and contact Cryptopia Support (as I did days ago!). The issue was "RIGHTFULLY" closed. And no, I am not a member of the Electroneum team.

Again... you don't contact the central bank if your local bank is having issues!? right?

Cryptopia Coin Info: https://www.cryptopia.co.nz/CoinInfo/?coin=ETN

**Comment by MynxGithub** [comment]
@jpenner123 Thank you, I never knew there was a coin info link, ETN seems to be back up, and tbh a response from here in 1-3 days with some form of information is better than 0 information for at least 28 days from Cryptopia.

**Comment by wcchye** [comment]
My transaction still not yet receive Electroneum since 2 week back. Is that will lost my ETN?
