### ISSUE TITLE
Unfair advantage for pools with massive hashrate **Copied**

### ISSUE THREAD

**Issue by mobias** [electroneum/electroneum#197]
Hi Electroneum Team, thanks for the great work you are doing. Looking forward to ETN taking over the World soon :)

We are running a small pool at https://alhafeez.tech/etn/ that was doing quite well until network hash-rate increased and, more importantly, most of the hashing power became concentrated on few pools like Nanopool (https://etn.nanopool.org/) or Spacepools (https://etn.spacepools.org/). Spacepools is much slower now but it was running 100 MH+ before Nanopool started.

Since network speed went significantly up, we observe the efficiency of **all pools going down**, even the big ones report a lot of extra effort (e.g. quite a few high efforts %s here https://alhafeez.tech/etn/#pool_blocks). Even what-to-mine has a notice about negative luck on ETN mining. I think this is happening because replication of new blocks are taking about the same time it takes to find a new block so the network is in constant update mode. Add rebuild operations (caused by forks) to the picture and you can see it looks quite grim. If pool manages to attract about half of the network hashing power or more, this is less of the problem for them because they start with new block immediately after they found the last one and chances are high they get the new one too so other pools have nothing to do but just refresh their daemons without making even one attempt at finding the next block.

Is it possible (or did you even consider this) to make an arbitrary increase of the difficulty to bring block detection time above 5 minutes so all pools have chances to find a new block but not only the ones that occupy 50% of the network hashrate.

Hope this makes sense and other pool owners will join me in this request.

Kind regards
Al-Hafeez Technologies Team

**Comments**
Our pool died just because not getting any block even with hashing with 500 KH/s for 72 hours, that's sucks, all moved to mine another coin.

**Comment by Cideg** [comment]
If you look at most pool's, there is also an access to orphaned blocks. Again, a support for finally has to be offered. But nobody seems to care.

**Comment by mobias** [comment]
can you explain a little bit more, please?
Thanks

**Comment by ghost** [comment]
Just so we've got the relevant numbers:
Your hashing power: 500kH/s
Network hashing power: 275mH/s
So your hashing power as a fraction of the total hashing power of the network would be: 
500 / 275*10^3 = 0.00181818181
There are approximately 1440 blocks a day on average as far as I'm aware.
You should therefore get 2.6181818064 blocks per day on average.
Firstly, It isn't unrealistic for you to go 3 days without getting a block (although it's very unlikely).

Secondly, to be clear, are you suggesting we change

#define DIFFICULTY_TARGET                               60  // seconds

to 5 minutes so that this 'replication' process takes a smaller proportion of time compared to the target block detection time?

**Comment by mobias** [comment]
Sorry for late reply. We close our electroneum mining pool because of this issue & I don't suggest a proper solution at this time. 

Maybe Later,
Thanks

**Comment by mobias** [comment]
**Copied**

I think a viable solution would be to do this:

- Set a mandatory timer of at least 5 minutes from the time of solving a block to picking up a new block generated.

- If a pool gets more than 20% hashing power of the entire blockchain, and the generation timer has not expired, the pool has to pick up a mandatory orphan block dumped by smaller pools.

- Any pools with less than 20% hashing power would be able to automatically dump an orphan block back into the blockchain and pick up a freshly generated block if one exists on the waiting list. No pools with less than 20% hashing power are required to solve an orphan block.

- If no orphan blocks exist in the network, all pools regardless of hashing power must still wait until the timer expires to pick up a new block, the highest priority of pickup is reserved for lowest hashing power.

**Comment by RustyBlock** [comment]
In the new release (after 30th of May) we are getting 2 minutes for the block. Not 5, if course, but still good.
Mind that issie with block time is separate from asics problem. I started this request before any asics arrived. 
Block timing of 1 minute is not a good choice because it's almost equal to the time needed to propagate the block data to most of the nodes. This means big part of the hashing power goes wasted, working for a block that is gone already, or creating orphans. 

New update introduces 2 minutes block time and revised block reward because now miners will be finding blocks less often. 
Combined with anti-asic measures, it will be awesome for the community.

**Comment by Cideg** [comment]
Unfortunately, you realize that nothing has changed.

According to some surveys, many pool operators have to fight with very large current blocks.
The current cost is well over 150%, with small pools.
And if these are not successful, it is a pity that the ETN team offers no solutions.

**Comment by RustyBlock** [comment]
Most issues addressed in v2 release. People "bombing" network with nicehash is a different issue, at least it's just now and everyone has equal opportunity, big or small. I think Electroneum team can close this record. Thank you for listening!
