### ISSUE TITLE
Is electroneum still asic resistant ?

### ISSUE THREAD

**Issue by QwertyJack** [electroneum/electroneum#208]
Yes according to WP.
When to fork?

**Comment by ghost** [comment]
No but it will be after the next fork. Testing is being performed right now.

**Comment by BigslimVdub** [comment]
Where is the testnet for public use?

**Comment by QwertyJack** [comment]
I cant wait

**Comment by felipe-vvoosh** [comment]
So slow...

**Comment by GoldKimber-Mining** [comment]
Forking away from the current Algorithm only hurts the project overall.  Slower network, retarded adoption, ignoring innovation, etc...  You should learn from the Monero 5-way split..... where 4 of the 5 have decided to stay on the current algorithm.  As miners, you'd be a fool to spend $200,000 - $1,000,000 on the same GPU hardware to be able to hash at the same rates as ASIC hardware that only cost $2,000 and uses far less electricity.  But hey, what do I know?  Forking is for little boys who want to be poor and don't want to make $50,000 a month.  You'd rather be poor and make $1.00 a day and act like you are geniuses because you finally got your Cortana to stop loading... WTFU!  Wake the F Up!

**Comment by GoldKimber-Mining** [comment]
I've been mining with GPUs for years.  I'm one of you too!  I've just made the decision to not accept such low wages in return for providing a service to the Developers of these coins.  (Who are hard working folks too, and who should also want to see their coin go up in value and make lots of money).  There is more than one way to support your favorite network.  Quit being married to your hardware that doesn't love you back!  If you want to see your coin survive long-term, make it extensible so folks can make good money over a really long period of time, even with ASICS on the blockchain.  Why don't you build that technology in?

**Comment by felipe-vvoosh** [comment]
All other coins have updated their algos already. The ETN network is around 650 MH/s atm. I’m not mining this shitcoin anymore and I shouldn’t care but it’s a shame that even when it’s clear the ETN team is being lazy and slow there are still stupid fan boys here to defend them. Just look the price of the coin, it reflects how bad the situation is. Yes, it is a dead coin, and it’s because of you, fan boys.

**Comment by Unyxos** [comment]
Felipe, go apply for a job if it sounds so easy for you to do this. :)

**Comment by felipe-vvoosh** [comment]
Just use your brain Unyxos, even Turtle Coin updated, who’s the turtle now? And check this:
https://github.com/xmrig/xmrig/issues/482

**Comment by QwertyJack** [comment]
Totally agree with @felipe-vvoosh.
The fork is not easy and ETN says it will soon.
But I still think it's dead.

**Comment by felipe-vvoosh** [comment]
"soon" is not a date... That's totally unprofessional... But the fan boys support all this.

**Comment by ghost** [comment]
Join this group if you support a fork and invite as many people as you can : https://t.me/etn_fork_supporters

**Comment by lkelemen** [comment]
Instead of ASIC resistance wouldn't it be better and simpler to implement a 10-100 ETN transaction fee for wallets having bigger than 5-10kh/s ?

**Comment by electroneumRepo** [comment]
Asic resistance will be implemented on May 30th along with many changes. Thanks. 
https://electroneum.com/2018/04/25/blockchain-update/

**Comment by creolis** [comment]
A clarifying note for everybody who stumbles upon this issue:

After this ticket was closed, ASIC Resistance WAS introduced with Block 307500
and is now scheduled to be removed again (so that ASICs will be back on Electroneum) with blockheight 324500.

The intent for this message is solely informational. The reasons or circumstances that led to this decisions are not to discussed here and a totally different thing :)
