### ISSUE TITLE
Is ETn a dead Coin??????? 

### ISSUE THREAD

**Issue by ghost** [electroneum/electroneum#213]
Is etn a dead coin and will not survive in 2018? I do not believe that any ASIC presence is introduced, as is the case with other coins, nor is the original objective pursued. Is ETN in the end? Yes sure. Neither an immediate Forkhelp is delivered, Dear first make a trip around the world, and consoling the users by a Hypocrite text. This is how the words from ETN sounded. Making your own bags and dropping the user makes mining fun. 

Thanks ETN but that's the last one.

**Comment by Cideg** [comment]
Somehow he is right, with a difficulty of: 28370457759 the little ones get nothing more. Please switch ETN to v7 immediately.

**Comment by felipe-vvoosh** [comment]
ETN team is slower than Turtle Coin team... And they ban you from Telegram if you say any truth there.

**Comment by felipe-vvoosh** [comment]
ASIC miners are just laughing right now, the network hash rate is above 500 MH/s hahahha

**Comment by cryptobender69** [comment]
Will be dead soon.

**Comment by ETN-A** [comment]
None of the above comments are GitHub material really, are they? Close it.

**Comment by tadangky** [comment]
hahaha, they don't care

**Comment by ghost** [comment]
Join this group if you support a fork and invite as many people as you can : https://t.me/etn_fork_supporters

**Comment by lkelemen** [comment]
Instead of ASIC resistance wouldn't it be better and simpler to implement a 10-100 ETN transaction fee for wallets having bigger than 5-10kh/s ?

**Comment by ghost** [comment]
@lkelemen never read so a stupid idea. i4m already 2.5 Kh/s with only 3 GPU. Do you even know what represent a 10 ETN fees on each Tx if it start at 5 kh/s ? aha you make me laugh 🤣

**Comment by lkelemen** [comment]
@natizyskunk OK, let's make an exception to the rule I proposed. People with letters n.a.t.z.i. in their nick pay 0 ETN transaction fee. Better now? 👍

**Comment by DrEhsan** [comment]
electroneum team got 40M$ from people and they have stopped electroneum right now because it is now a scam project which had the purpose to stole people fund with yellow claims!
so it is already a dead coin! fuck it

**Comment by Unyxos** [comment]
Dead ? Let me laugh please. Stopped ? Let me laugh even more, IPS beta is almost about to be launched, iPhone app in beta testing, got listed today on a top 20 exchange and some other stuff. Before crying and shouting that BS, do your own researches.

**Comment by DrEhsan** [comment]
@Unyxos 
According to coinmarketcap : 

CoinBene is Rank 30
cryptopia is Rank 92
Kucoin is Rank 58
Liquid is Rank 83
Bitbns is not in range of 100 top exchanges!
TradeOgre is not in range of 100 top exchanges!
Cryptomate is not in range of 100 top exchanges!
Cryptohub is not in range of 100 top exchanges!

These are exchanges that ETN is trading on them recently

so can you please tell us which one of this exchanges are in top 20 high volume exchanges, Mr.Researcher?
this shows you never had the time to search the web Mr.Researcher!

do you know what the dead means? the dead means it is going to be 0 $ as soon as possible! it is under ico price! the trade volume is only 20btc right now! even the shit coins are more than ETN trade volume 
Etn has the most slow developers on world with confusing strategy! they committed ASIC resistance and then revoke it day after why? because have no plan! have no strategy and it is just going to die 
the value is 79 sattoshi right now :)) if you dont like to name it as dead coin then you can use shit coin if you prefer!
