### ISSUE TITLE
Electroneumd data usage

### ISSUE THREAD

**Issue by FarhoodKa** [electroneum/electroneum#292]
Hi
I've been using electroneumd.exe for 4 days and it used over 30 gigabyte.
My blockchain node was 545 days behind and now it's 102 days behind.
Is Electroneumd using a lot data or is that some kind of problem ?
Please help me out

**Comment by andrepatta** [comment]
Hi @farhood2020 ,

It's normal that the Electroneum Daemon takes a few days to sync depending on your network speeds. The blockchain is really huge (around 36GB) due to the high number of transactions on the network.

You should be fine just by letting your ETN Daemon up & running so it can sync to the network.

Thanks

**Comment by FarhoodKa** [comment]
Hi @andrepatta
Tnx a lot for your help.
❤❤❤
