### ISSUE TITLE
ETN needs to update a patch to prevent lone blocks

### ISSUE THREAD

**Issue by hsb1115284873** [electroneum/electroneum#309]
ETN needs to update a patch to prevent lone blocks @ChrisCharrison

**Comment by ghost** [comment]
We are exploring all options here. 
Please bear in mind that it is currently the pools choice whether or not to fill the blocks. There isn't a flaw in the code that's preventing them from filling them. 
One of our pools explained why they were doing it and the fix for their genuine performance related issue will be released in the next update.
