### ISSUE TITLE
How long is the balance unlocked

### ISSUE THREAD

**Issue by uranus97s** [electroneum/electroneum#321]
Currently my balance is 1000ETN, but my unlock balance is 0. So how long will it take me to use my balance? I am not working on privatenet network so is there any way to make the switch from balance to unlock balance. Help me! Please

**Comment by uranus97s** [comment]
Thank you for your help. But I need a tutorial on how to fix source code.

**Comment by ghost** [comment]
The unlock time is 10 blocks (10 confirmations) on the same blockchain for ETN received from someone else, or as a change output, and 18 blocks for ETN received from coinbase emissions. This is the same regardless of whether you're on the testnet or mainnet. However for testing purposes, you may change the values 
CRYPTONOTE_MINED_MONEY_UNLOCK_WINDOW
and
CRYPTONOTE_DEFAULT_TX_SPENDABLE_AGE
in order to experiment with different unlock times.
