### ISSUE TITLE
5.0.0.3-osx-x86.tar on Big Sur OS X problem

### ISSUE THREAD

**Issue by Hemulen2** [electroneum/electroneum#390]
Have been using Daemon and CLI-wallet v4.0.0.1 on an old Macbook (Big Sur 11.7.10). Downloaded v5.0.0.3 and it doesn't work. 
Is it possible to run the new version on Big Sur?
Here is the error I get when I start electroneumd:
![image](https://github.com/electroneum/electroneum/assets/162511051/1a6ff4b6-5750-454e-9a16-642bb3b153d6)

**Comment by chrischarlesharrison** [comment]
You're running the old binaries 5.0.0.2 rather than 5.0.0.3. Please download the new ones
[5.0.0.3-osx-x86.tar](https://github.com/electroneum/electroneum/releases/download/v5.0.0.3/5.0.0.3-osx-x86.tar)
I'm guessing the outcome will be the same though, so you should update your macOS version. We don't provide long term support for old version of OSX. That's not to say that binaries built on OSX14 wont work on earlier versions; often they do, but there is no guarantee. 

Alternatively, you can just compile the programs yourself. It's fairly easy:

`cd ~ && git clone --recursive https://github.com/electroneum/electroneum`
`cd electroneum/contrib/brew`
`brew bundle`
`cd ~/electroneum`
`git submodule init && git submodule update`
`make`

**Comment by Hemulen2** [comment]
Thank you for your reply. I have download 5.0.0.3 and it makes no difference (macbook mid-2014, big sur 11.7.10)


 ~ % /Volumes/SSD\ Rob/ETN-cli\ wallet/5.0.0.3-osx-x86/electroneumd ; exit;
dyld: Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
  Referenced from: /Volumes/SSD Rob/ETN-cli wallet/5.0.0.3-osx-x86/electroneumd (which was built for Mac OS X 14.0)
  Expected in: /usr/lib/libc++.1.dylib

zsh: abort      /Volumes/SSD\ Rob/ETN-cli\ wallet/5.0.0.3-osx-x86/electroneumd
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Processen slutförd]

**Comment by Hemulen2** [comment]
Unfortunatley It’s no longer possible to upgrade the osx. I’ll try to compile it. Maybe its time for a new computer😁
