### ISSUE TITLE
Daemon error: Failed to update txpool transaction metadata: Error finding txpool tx meta: MDB_NOTFOUND: No matching key/data pair found

### ISSUE THREAD

**Issue by sleever** [electroneum/electroneum#46]
Hello,

I  hope you can help us out. We're running a pool at https://etnpool.net and are, as of last friday morning (8th of December), experiencing the error in the attached file concerning:

2017-12-14 08:26:29.870	[P2P4]	ERROR	txpool	src/cryptonote_core/tx_pool.cpp:516	Failed to update txpool transaction metadata: Error finding txpool tx meta: MDB_NOTFOUND: No matching key/data pair found

We've tried everything to resolve this, and with everything I mean:

1. Rebuilding the blockchain from scratch (miners were still connected during this process).
2. Rebuilding the block externally, uploading it to the server while miners were not connected.
3. Updating the wallet to the latest version & rebuilding the blockchain, again, externally.
4. Completely reinstalling the server by reinstalling the OS and start off new. We've also changed the ports to mine on to make sure no miner is submitting corrupt shares from before the crash. The blockchain has also been rebuild on this system from scratch.

As you might understand we're quite lost here and would like to know what might cause this issue and, of course, how to solve it. We're under the assumption that due to this error our pool is not possible to correctly talk with the blockchain and thus is not able to submit blocks to the chain (not finding blocks). This issue has currently caused our pool to run dry so this is our last resort.

Additional details:

- We're running our Redis server separately from our main pool server to maintain stats, I am under the assumption that this should not be a problem as the daemon doesn't talk with Redis.

I thank everybody very much in advance for looking into this and helping us out as we really want to start mining again and be of service to our miners.

Best regards,
Stefan

[20171214-MDB_NOTFOUND_no_matching_key_data_pair.txt](https://github.com/electroneum/electroneum/files/1558515/20171214-MDB_NOTFOUND_no_matching_key_data_pair.txt)

**Comment by ddvs1** [comment]
Same prob here.

**Comment by phil2cr** [comment]
Hi,
i did post on the monero thread, but i will post here also because i see that using electroneumd
I think i don't found block in the same way @sleever did describe.
But as the pool begin after the 10 of december is see the error message "Daemon error: Failed to update txpool transaction metadata: Error finding txpool tx meta: MDB_NOTFOUND: No matching key/data pair found" from that time (i have no thing before).

I have Ubuntu 14.4.05
the daemon is linux-x64-0.11.0.0 (from linux-x64-0.11.0.0.zip)
nodejs: node-v0.10.48-linux-x64.tar.gz
db: redis-2.6.14.tar.gz
pool: github.com/fancoder/cryptonote-universal-pool.git

I didn't start the RPC wallet. Only the daemon is ruuning.
- - - - -
* I got the exactly the same problem (with electroneum), somebody did davance on the problem ? found a solution ?

1) I use :
./electroneumd --db-salvage
(from monero)
The program seems to work but take 3 or 4 second to finish. I didn't check the result.

I prefer to run this solution first:
2) 
- I have deleted the data.mdb and lock.mdb file to resync all the block chain
- ./electroneumd
...sync...sync...
i don't know the result for now

- - - - -
I would like to have the feeling of everybody.
I did see in the code the result of the function was changed from the return value to a boolean value. I think that is to check the validity of the block.
The problem that happend with the block is coming (from your point of vue) more probably from:

a pbm in a node of the pool (so all pools have the same problem) ?
a pbm on the local node (only one pool have a probleme from time to time) ?
it was caused by the dameon of the blockchain ?
it was caused by a mining software ?
it is a glitch in the transmit of the blockchain ?

And also how this problem make we stop receving block ?

**Comment by phil2cr** [comment]
Ok, the sync is done i didn't notice an problem : no error.

If i understand well the problem we did have must be local ?

I will wait about 24h like that because in the logs i did notice the problem occured once a day.
to see what append.

Also i did change the config of the pool (config.json):
I put trust_share = false .
I don't deeply understand the use of that, but it look like there is a check between miners and the pool. So it could not hurt (before i let trust_share = true ).

keep you updated, bye.

**Comment by phil2cr** [comment]
ok,
That failled.
i will have to apply the patch.

**Comment by ma1100** [comment]
Have you come up with a solution yet?

**Comment by logingood** [comment]
I don't think that it has any impact on the ability to find blocks. I'm running electroneumd daemon without mining on the other node, with the block chain that was synced from zero, with DB options `--db-sync-mode safe --block-sync-size 20`. I already saw this error 4 times over a week. 

I have certain concerns about electroneumd in general because right now I don't see any improvements comparing to `monerod` project and at the moment it basically runs several hundred commits older version of `monerod`. There is no development happening in `electroneum` repository, last meaningful commit was more than a month ago. Probably this blockchain is facing scaling challenges which no one is willing to address. I found last block 19 days ago and this round is almost 300%. So I don't think that those errors affect block mining, it is just network itself: block substitution and massive pools, like nanopool.

```
2018-01-07 09:16:47.940 [P2P1]  INFO    stacktrace      src/common/stack_trace.cpp:120  Exception: cryptonote::DB_ERROR
2018-01-07 09:16:47.949 [P2P1]  ERROR   txpool  src/cryptonote_core/tx_pool.cpp:516     Failed to update txpool transaction metadata: Error finding txpool tx meta: MDB_NOTFOUND: No matching key/data pair found
2018-01-07 14:00:26.206 [P2P9]  INFO    stacktrace      src/common/stack_trace.cpp:120  Exception: cryptonote::DB_ERROR
2018-01-07 14:00:26.224 [P2P9]  ERROR   txpool  src/cryptonote_core/tx_pool.cpp:516     Failed to update txpool transaction metadata: Error finding txpool tx meta: MDB_NOTFOUND: No matching key/data pair found
2018-01-10 09:00:31.600 [P2P6]  INFO    stacktrace      src/common/stack_trace.cpp:120  Exception: cryptonote::DB_ERROR
2018-01-10 09:00:31.612 [P2P6]  ERROR   txpool  src/cryptonote_core/tx_pool.cpp:516     Failed to update txpool transaction metadata: Error finding txpool tx meta: MDB_NOTFOUND: No matching key/data pair found
2018-01-13 11:25:13.032 [P2P9]  INFO    stacktrace      src/common/stack_trace.cpp:120  Exception: cryptonote::DB_ERROR
2018-01-13 11:25:13.064 [P2P9]  ERROR   txpool  src/cryptonote_core/tx_pool.cpp:516     Failed to update txpool transaction metadata: Error finding txpool tx meta: MDB_NOTFOUND: No matching key/data pair found
```

**Comment by AwadElkarem** [comment]
i have the same problem , dont tell me to resync , it took me days to sync

is there a fix

**Comment by prox443** [comment]
@AwadElkarem  pb resolved ?

**Comment by ghost** [comment]
We are soon releasing a major release (non fork) that should take care of this issue. Pools are also now obsolete.
