### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by nasopraso** [electroneum/electroneum#62]
Why when I have complete download of the blockchain let say till 78400 block my CLI wallet start to syncing from block 68000. It takes a lot of time!

Is it possible to sync from where is stopped last time?

**Comment by electroneumRepo** [comment]
@nasopraso Firstly, when you create a new wallet. You can choose when to start the sync from.
Secondly, when you re-open a previously saved wallet. It will sync from the last time it was active. The longer the amount of time, the longer it will take to sync.

I hope this helps

**Comment by nasopraso** [comment]
it's always start from block 65000...now is 92052
How can I change that settings?

**Comment by nasopraso** [comment]
btw the other issue is - please make the users to choose were to store the blockchain database!! In C:\User\App\... is not good....
C: drive not have too much space..most of the people are with SSD around 120 GB...windows takes about 70-90GB..

**Comment by electroneumRepo** [comment]
@nasopraso I would say you are no closing your wallet correctly. Use `save` and then `exit` to close your wallet. This should leave it stored at the current height.

You can change the data directory by using the `--data-dir` flag when starting the daemon. `C:` is used by default because not everybody has a second drive.
