### ISSUE TITLE
Change default blockchain location

### ISSUE THREAD

**Issue by lozitskiys** [electroneum/electroneum#74]
I'd like to move it from default location C:\ProgramData\electroneum to separate HDD.
Is it possible?

**Comment by electroneumRepo** [comment]
Hi,

There is a command line flag you can use when you start the daemon.

Open a command prompt window and navigate to the directory where you have the daemon file.
Run electroneumd.exe --data-dir="C:\path\to\desired\directory"

If you already have the blockchain downloaded you should copy it to the location first otherwise it will trigger a full re-download of the blockchain.

I hope this helps.

**Comment by lozitskiys** [comment]
Great, thank you!

**Comment by RonerCodes** [comment]
Question:   Is the ProgramData directory hardcoded into electroneumd.exe or does it read the environment variables?  I've tried changing both the ProgramData variable and AllUsersProfiles variable to the separate HDD and electroneumd was still writing to the default ProgramData directory.
