### ISSUE TITLE
Not receiving Coins in Offline wallet. 

### ISSUE THREAD

**Issue by CryptoParker** [electroneum/electroneum#79]
Hi,
I hope you guys can help me as i am new to this mining business. I have the beginner program mining with my CPU and i have also installed the direct mining software, were i have successfully synced to eletroneumd.exe. Both were installed from electroneum website. 
On the screen,  i am getting these messages, see below;

2017-12-30 06:02:20.584 [P2P0]  WARN    net.dns src/common/dns_utils.cpp:487    WARNING: no two valid ElectroneumPulse DNS checkpoint records were received
2017-12-30 07:02:55.234 [P2P6]  WARN    net.dns src/common/dns_utils.cpp:487    WARNING: no two valid ElectroneumPulse DNS checkpoint records were received
2017-12-30 07:04:41.155 [P2P7]  INFO    global  src/cryptonote_core/blockchain.cpp:1428 [1;34m----- BLOCK ADDED AS ALTERNATIVE ON HEIGHT 89882
id:     <0caf21a71667164f0d99ed3f2a405cd5317bfee201dbdba5def130ccd7c83495>
PoW:    <ff3a8e1d827d13f75b3875322769c46fa45c530f5c36aa5ebe9f400200000000>
difficulty:     12450686443[0m
2017-12-30 08:01:25.965 [P2P4]  INFO    global  src/cryptonote_core/blockchain.cpp:1428 [1;34m----- BLOCK ADDED AS ALTERNATIVE ON HEIGHT 89935
id:     <ead797e3418fa36d5294e788f01e50cd6174146652399efe834f7ff8a61c75ce>
PoW:    <209346416e16953ff40b7d192726236ed03a010b8dd9d4a01e03845200000000>
difficulty:     12632609745[0m
2017-12-30 08:03:48.417 [P2P0]  WARN    net.dns src/common/dns_utils.cpp:487    WARNING: no two valid ElectroneumPulse DNS checkpoint records were received

Now i like to point out, that i have never closed electroneumd.exe while my CPU and GPU mined. I downloaded CCminer, and i used this "whatever you call it" with CC miner to connect to the right pool?

C:\Users\josh_\Desktop\CC miner>ccminer-x64.exe -a cryptonight -o stratum+tcp://eupool.electroneum.com:7777 -u etnkGy9nWnPahEBY7zfrEhZJSoVHpBYzDTtMqa8PmoLXPm6XxPfEtMjP9NkuCmkiwHW9dePjFsJ48NXpCuJH7Bnv2q3CsnprNg p x

Forgive my terminology, i am noobie. I am using a 4790k CPU and 980ti for GPU. Please advice if i am doing something wrong, or whether i just need to to patient to see the coins appear. Just thought that after 20 hours of mining @ 470h/s with my GPU, and around 30h/s with my CPU, i thought i'd have at least some coins by now.

**Comment by ZielarSRC** [comment]
C:\Users\josh_\Desktop\CC miner>ccminer-x64.exe -a cryptonight -o stratum+tcp://eupool.electroneum.com:7777 -u etnkGy9nWnPahEBY7zfrEhZJSoVHpBYzDTtMqa8PmoLXPm6XxPfEtMjP9NkuCmkiwHW9dePjFsJ48NXpCuJH7Bnv2q3CsnprNg p x 


*** try this in CMD
ccminer-x64.exe -a cryptonight -o stratum+tcp://eupool.electroneum.com:7777 -u etnkGy9nWnPahEBY7zfrEhZJSoVHpBYzDTtMqa8PmoLXPm6XxPfEtMjP9NkuCmkiwHW9dePjFsJ48NXpCuJH7Bnv2q3CsnprNg -p x

**Comment by JASHIKO** [comment]
I'm currently having a similar problem. I have thousands of missing coins which I mined during the first 2 weeks after launch. I have the transactions that state they have been sent and paid to my wallet address. (the addresses are entered correctly) I was using the official CPU miner and the official eu-mining pool. So far only 650 of several thousand have made it to my offline wallet. I have mined from other sources and those payments have made it to my wallet, so I'm guessing the issue is with the official miner and pool. 

Has anyone else had a similar issue? I emailed ETN (raised a ticket) and they said they are aware of the problem and that the coins aren't missing.... That was over a month ago now....... Any suggestions?
